import { BillingCycle, SubscriptionStatus } from '../types';

export interface SubscriptionPreset {
  name: string;
  category: string;
  price: number;
  currency: string;
  billing_cycle: BillingCycle;
  website: string;
  logo: string;
  color: string;
  notes?: string;
  cancellation_url?: string;
}

export const POPULAR_PRESETS: SubscriptionPreset[] = [
  {
    name: 'Netflix',
    category: 'Entertainment & Streaming',
    price: 15.49,
    currency: 'USD',
    billing_cycle: 'monthly',
    website: 'https://netflix.com',
    logo: 'https://assets.nflxext.com/ffe/siteui/common/icons/nficon2023.ico',
    color: '#E50914',
    cancellation_url: 'https://www.netflix.com/cancelplan',
    notes: 'Standard plan with HD streaming',
  },
  {
    name: 'Spotify',
    category: 'Music & Audio',
    price: 11.99,
    currency: 'USD',
    billing_cycle: 'monthly',
    website: 'https://spotify.com',
    logo: 'https://open.spotifycdn.com/cdn/images/favicon.0f31d2ea.ico',
    color: '#1DB954',
    cancellation_url: 'https://www.spotify.com/account/subscription/',
    notes: 'Individual premium ad-free plan',
  },
  {
    name: 'ChatGPT Plus',
    category: 'Productivity & Work',
    price: 20.00,
    currency: 'USD',
    billing_cycle: 'monthly',
    website: 'https://chatgpt.com',
    logo: 'https://chatgpt.com/favicon.ico',
    color: '#10A37F',
    cancellation_url: 'https://chatgpt.com/#settings',
    notes: 'OpenAI GPT-4o and advanced analysis',
  },
  {
    name: 'GitHub Copilot',
    category: 'Cloud & Developer Tools',
    price: 10.00,
    currency: 'USD',
    billing_cycle: 'monthly',
    website: 'https://github.com/features/copilot',
    logo: 'https://github.githubassets.com/favicons/favicon.png',
    color: '#24292F',
    cancellation_url: 'https://github.com/settings/billing',
    notes: 'AI code completion and suggestions',
  },
  {
    name: 'YouTube Premium',
    category: 'Entertainment & Streaming',
    price: 13.99,
    currency: 'USD',
    billing_cycle: 'monthly',
    website: 'https://youtube.com/premium',
    logo: 'https://www.youtube.com/s/desktop/990faef5/img/favicon_144x144.png',
    color: '#FF0000',
    cancellation_url: 'https://www.youtube.com/paid_memberships',
    notes: 'Ad-free videos and YouTube Music included',
  },
  {
    name: 'Amazon Prime',
    category: 'Entertainment & Streaming',
    price: 139.00,
    currency: 'USD',
    billing_cycle: 'yearly',
    website: 'https://amazon.com',
    logo: 'https://www.amazon.com/favicon.ico',
    color: '#FF9900',
    cancellation_url: 'https://www.amazon.com/mc/manage',
    notes: 'Includes free delivery, Prime Video, and Prime Gaming',
  },
  {
    name: 'Figma Professional',
    category: 'Productivity & Work',
    price: 15.00,
    currency: 'USD',
    billing_cycle: 'monthly',
    website: 'https://figma.com',
    logo: 'https://static.figma.com/app/icon/1/favicon.ico',
    color: '#F24E1E',
    cancellation_url: 'https://figma.com/settings',
    notes: 'Design & prototyping collaboration',
  },
  {
    name: 'Notion Plus',
    category: 'Productivity & Work',
    price: 10.00,
    currency: 'USD',
    billing_cycle: 'monthly',
    website: 'https://notion.so',
    logo: 'https://www.notion.so/images/favicon.ico',
    color: '#000000',
    cancellation_url: 'https://www.notion.so/settings',
    notes: 'All-in-one workspace and docs',
  },
  {
    name: 'Apple iCloud+',
    category: 'Utilities & Software',
    price: 2.99,
    currency: 'USD',
    billing_cycle: 'monthly',
    website: 'https://apple.com/icloud',
    logo: 'https://www.apple.com/favicon.ico',
    color: '#0071E3',
    cancellation_url: 'https://support.apple.com/HT207594',
    notes: '200GB cloud storage & Private Relay',
  },
  {
    name: 'Disney+',
    category: 'Entertainment & Streaming',
    price: 13.99,
    currency: 'USD',
    billing_cycle: 'monthly',
    website: 'https://disneyplus.com',
    logo: 'https://static-assets.bamgrid.com/product/disneyplus/favicons/favicon.ico',
    color: '#113CCF',
    cancellation_url: 'https://www.disneyplus.com/account',
    notes: 'Disney, Pixar, Marvel, Star Wars & Nat Geo',
  },
  {
    name: 'Adobe Creative Cloud',
    category: 'Utilities & Software',
    price: 54.99,
    currency: 'USD',
    billing_cycle: 'monthly',
    website: 'https://adobe.com',
    logo: 'https://www.adobe.com/favicon.ico',
    color: '#DA1F26',
    cancellation_url: 'https://account.adobe.com/plans',
    notes: 'Photoshop, Illustrator, Premiere Pro suite',
  },
  {
    name: 'Vercel Pro',
    category: 'Cloud & Developer Tools',
    price: 20.00,
    currency: 'USD',
    billing_cycle: 'monthly',
    website: 'https://vercel.com',
    logo: 'https://assets.vercel.com/image/upload/front/favicon/vercel/favicon.ico',
    color: '#000000',
    cancellation_url: 'https://vercel.com/dashboard/billing',
    notes: 'Hosting and edge serverless platform',
  },
  {
    name: 'Xbox Game Pass Ultimate',
    category: 'Gaming',
    price: 16.99,
    currency: 'USD',
    billing_cycle: 'monthly',
    website: 'https://xbox.com/gamepass',
    logo: 'https://www.xbox.com/favicon.ico',
    color: '#107C10',
    cancellation_url: 'https://account.microsoft.com/services',
    notes: 'Hundreds of games on PC, Console, Cloud',
  },
  {
    name: 'Strava Summit',
    category: 'Health & Fitness',
    price: 11.99,
    currency: 'USD',
    billing_cycle: 'monthly',
    website: 'https://strava.com',
    logo: 'https://web-assets.strava.com/favicons/favicon.ico',
    color: '#FC4C02',
    cancellation_url: 'https://www.strava.com/settings/subscription',
    notes: 'Running & cycling GPS tracking and analytics',
  },
];
